[PCX-1935] Fix OSLog issues
optile/checkout-ios pull request #123
Opened 2021-08-20 14:12 UTC by caiomello

- Replaced instances of `import OSLog` with `import os.log` ([More info](https://developer.apple.com/forums/thread/661061))
- Replaced calls to `os_log` with instances of `Logger`

2021-08-23 10:53 UTC, Sorix requested changes

2021-08-23 10:53 UTC, Sorix commented on .gitignore
> +.DS_Store
I prefer to keep OS-related files in [global gitignore](https://github.com/github/gitignore/blob/master/Global/macOS.gitignore) rather than in repo-specific. @siebeprojects what do you think about that?

2021-08-23 10:53 UTC, Sorix commented on Sources/Core/log.swift
>  func log(_ type: LogType, _ message: StaticString, _ args: CVarArg...) {
I think we should get rid of duplication: `InternalError().log` and global `log()`. Let's keep only one function (I think global `log()` should be eliminated but it's up to you to decide).

2021-08-23 10:53 UTC, Sorix commented on Sources/Core/log.swift
> +        let logger = Logger(subsystem: Bundle.frameworkIdentifier + ".network", category: "Log")
That's not a network subsystem (it's a global function). If you decide to remove that function, that comment doesn't matter in another case we should remove it.

```suggestion
        let logger = Logger(subsystem: Bundle.frameworkIdentifier, category: "Log")
```

2021-08-23 13:18 UTC, caiomello commented on .gitignore
> +.DS_Store
I wasn't aware of this, good to know! Still, any other/future dev that doesn't have a global gitignore will run into this, and I don't see any reason not to have this in the local ignore anyway... I'll revert the change.

2021-08-23 13:37 UTC, caiomello commented on Sources/Core/log.swift
>  func log(_ type: LogType, _ message: StaticString, _ args: CVarArg...) {
Now that I've looked into the code some more I think there are too many different mechanisms being used for logging. Sadly we cannot wrap `Logger` under an abstraction, so calls to `Logger` will always be pervasive throughout the codebase. What we can do instead is have a unified approach, where any usage of `Logger` follows the same pattern. Right now we have multiple helper `log` functions in different places, like in `log.swift`, `InternalError`, various local/public extensions, and as part of the `Request` protocol. It'd be great to streamline this, for example by enforcing that there must always be a local `logger` property that the object can use, like it's already implemented in the input and list view controllers.

2021-08-24 05:51 UTC, Sorix commented on Sources/Core/log.swift
>  func log(_ type: LogType, _ message: StaticString, _ args: CVarArg...) {
@caiomello please check 6874051ab8e0f8279fd823a0d304793050d8e893

2021-08-24 07:42 UTC, caiomello commented on Sources/Core/log.swift
>  func log(_ type: LogType, _ message: StaticString, _ args: CVarArg...) {
I was trying some stuff out yesterday and started with something like this:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/1280777/130576692-facec9b7-3530-46ef-a711-ce306da54675.png">

The protocol approach is good, I like it.

2021-08-24 15:24 UTC, Sorix approved these changes

2021-08-25 07:16 UTC, siebeprojects approved these changes

2021-08-25 07:45 UTC, Sorix commented
@caiomello please update from `develop`

2021-08-25 15:07 UTC, merged