[PCX-2012] Respect allowDelete on UPDATE flow
optile/checkout-ios pull request #132
Opened 2021-09-07 14:22 UTC by caiomello

2021-09-07 14:31 UTC, Sorix commented on Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift
> +        let isDeletable = registeredAccount.isDeletable
I think you could remove that line at all and just use `registeredAccount.isDeletable` here:

https://github.com/optile/checkout-ios/blob/45367564b15c38dfccfa6fc41829e013ee594d63/Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift#L89

2021-09-07 15:06 UTC, Sorix commented on Sources/UI/Service/PaymentSessionService/PaymentSessionProvider.swift
> +            isDeletable: listResult?.allowDelete == false ? false : true // Defined in https://optile.atlassian.net/browse/PCX-2012
It's hard readable (unwrapping + if in one line) , but it's up to you. I could just suggest to have a separate line for a comment to avoid too long line.

2021-09-07 15:11 UTC, caiomello commented on Sources/UI/Service/PaymentSessionService/PaymentSessionProvider.swift
> +            isDeletable: listResult?.allowDelete == false ? false : true // Defined in https://optile.atlassian.net/browse/PCX-2012
100% agree, I'll extract this value.

2021-09-07 15:17 UTC, Sorix commented
Waiting for #130 to merge, because `PaymentContext` was introduced there.

2021-09-07 15:32 UTC, Sorix commented on Sources/UI/Model/RegisteredAccount.swift
> +        self.isDeletable = isDeletable
You decided to make that decision inside `PaymenSession`, now we could have inconsistency that decision about `PaymentNetwork` is done inside `ModelTransformer`. But `PaymentNetwork` couldn't be deleted by design of that entity...

https://github.com/optile/checkout-ios/blob/0037e7f1168fb21032fe1c843ef31a630cc94a27/Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift#L150

We have the next options:
1. Add `let isDeletable = false` in `PaymentNetwork`.
2. Make decisions in `ModelTransformer`.
2. Keep it like now (it's also ok).

I think because of that problem I decided some time ago to make that decision on `ModelTranformer` to avoid it. I don't know the best way to deal with that.

2021-09-08 08:20 UTC, caiomello commented on Sources/UI/Model/RegisteredAccount.swift
> +        self.isDeletable = isDeletable
Moved to `ModelTransformer` in https://github.com/optile/checkout-ios/pull/132/commits/32ffe1edb5b938700b93acab50a4c451dd686268.

2021-09-08 08:23 UTC, Sorix requested changes
We have a UI test for the delete button that actually checks when that button should appear and when not.

UI tests doesn't support `allowDelete` flag, we should add support for it and test `CHARGE`, `UPDATE` flow with different flag states. There is a bunch of work for that :(.

https://github.com/optile/checkout-ios/blob/32ffe1edb5b938700b93acab50a4c451dd686268/ExampleCheckout/UITests/UpdateFlowTests.swift#L98-L126

2021-09-08 17:55 UTC, Sorix commented
@caiomello I think it will be better to create the new branch from `develop` and apply your changes to the new branch, than resolving that conflicts and finding the changes in code review that could accidentally lead to merging something unexpected.

2021-09-09 07:47 UTC, caiomello commented
> @caiomello I think it will be better to create the new branch from `develop` and apply your changes to the new branch, than resolving that conflicts and finding the changes in code review that could accidentally lead to merging something unexpected.

Very simple conflicts, no problem.

2021-09-09 13:23 UTC, caiomello commented on Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift
> +        }()
@Sorix @siebeprojects Please verify.

2021-09-09 13:44 UTC, Sorix commented on Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift
> +        }()
@caiomello Could you describe the purpose of `return (registeredAccount.isDeletable == false) ? false : true` Is registeredAccount still optional?

2021-09-09 13:52 UTC, caiomello commented on Sources/UI/Scenes/Input/Model/ModelTransformer/Input.ModelTransformer.swift
> +        }()
`registeredAccount`'s `isDeletable` is optional.

`(registeredAccount.isDeletable == false) ? false : true` represents "The delete payment method (trashcan) is available if and only if allowDelete in the LIST object is either set to true or undefined in UPDATE flow". So the result is false only is `registeredAccount.isDeletable` is false.

2021-09-10 08:22 UTC, Sorix commented on Sources/UI/Service/PaymentSessionService/PaymentSessionProvider.swift
> +        let context = PaymentContext(operationType: operation, extraElements: listResult?.extraElements, isDeletable: listResult?.allowDelete)
@caiomello I recommend avoiding increasing the count of `isDeletable` optionals in the code. I think it is better to set in the root to `true` or `false` to avoid those three-state Booleans in multiple places.

I think that logic should be located here, we could eliminate the backend's flaws with undefined Boolean and work with a precise state.

2021-09-10 08:49 UTC, Sorix commented on Sources/UI/Service/PaymentSessionService/PaymentSessionProvider.swift
> +        let context = PaymentContext(operationType: operation, extraElements: listResult?.extraElements, isDeletable: listResult?.allowDelete)
I could propose doing something like that:

```swift
private func createPaymentSession(from translations: DownloadTranslationService.Translations) throws -> PaymentSession {
    guard let operationType = listResult?.operationType else {
        throw InternalError(description: "Operation type or ListResult is not defined")
    }

    // PaymentSession.Operation contains only supported operation types by the framework
    guard let operation = PaymentSession.Operation(rawValue: operationType) else {
        throw InternalError(description: "Operation type is not known or supported: %@", operationType)
    }

    let isDeletable = isDeletable(allowDelete: listResult?.allowDelete, forOperationType: operationType)
    let context = PaymentContext(operationType: operation, extraElements: listResult?.extraElements, isDeletable: isDeletable)

    return .init(networks: translations.networks, accounts: translations.accounts, context: context)
}

/// Returns the defined deletable state according to https://optile.atlassian.net/browse/PCX-2012
private func isDeletable(allowDelete: Bool?, forOperationType operationType: String) -> Bool {
    switch operationType {
    // Return true if allowDelete is true or nil
    case "UPDATE":
        if (allowDelete == true) || (allowDelete == nil) {
            return true
        } else {
            return false
        }
    // Return true allowDelete is true; return false if allowDelete is nil or false
    case "CHARGE":
        // listResult.allowDelete is Optional
       return allowDelete == true
    default:
        return false
    }
}
```

2021-09-10 09:54 UTC, closed without merging