[PCX-2161] New file header template
optile/checkout-ios pull request #138
Opened 2021-09-23 08:09 UTC by caiomello

> Original PR: #133 

Added a new header template file that changes new file header comments to our custom format.

<img width="490" alt="image" src="https://user-images.githubusercontent.com/1280777/134473530-b75b55df-0af6-43da-9895-d6d85d17056b.png">

2021-09-23 08:16 UTC, siebeprojects approved these changes

2021-09-24 20:39 UTC, Sorix requested changes

2021-09-24 20:39 UTC, Sorix commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
```suggestion
// https://www.payoneer.com
```

2021-09-27 07:49 UTC, caiomello commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
Can we _add_ the slash? It looks better... I'll happily do a replace to add it on every file.

2021-09-27 12:07 UTC, Sorix commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
In my opinion, it doesn't look better. As well to do that, the header should be also replaced in other repositories using it. CC @siebeprojects

2021-09-27 12:09 UTC, caiomello commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
Ah this is used in other projects? I didn't know. In that case, nevermind my suggestion.

2021-09-27 14:44 UTC, Sorix commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
@caiomello, hmm, I still see the trailing slash, did you update it?

2021-09-27 14:48 UTC, caiomello commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
Ah I rebased to remove a commit without the ticket so the change was lost (force push/rebase 🙄). I'll remove it again...

2021-09-27 14:50 UTC, caiomello commented on PayoneerCheckout.xcworkspace/xcshareddata/IDETemplateMacros.plist
> +// https://www.payoneer.com/
Done.

2021-09-27 17:42 UTC, Sorix approved these changes
✅, I will need to reapprove after you update it from the base branch. I think you could wait for PRs: #142, #140 to be merged.

2021-09-29 06:47 UTC, Sorix commented
@caiomello, could you update the base branch? #142 will require QA so it will take time to complete it, so let's not rely on that PR.

2021-09-29 11:42 UTC, siebeprojects approved these changes

2021-09-29 11:43 UTC, merged