[PCX-2119] Replace Material components
optile/checkout-ios pull request #154
Opened 2021-11-08 10:03 UTC by caiomello

2021-11-16 15:25 UTC, caiomello commented on Sources/UI/Components/TextInputView/CALayer+Extensions.swift
> +extension CALayer {
[Core Animation](https://developer.apple.com/documentation/quartzcore), the underlying animation framework on Apple OSs.

2021-11-16 16:14 UTC, Sorix commented on Sources/UI/Components/TextInputView/CALayer+Extensions.swift
> +extension CALayer {
Old-style modules in iOS use prefixes, like *NS*String, *UI*TableView, *CA*Layer, etc.

2021-11-17 06:07 UTC, Sorix requested changes
1. I could say that animation issues are worse than I expected looking at videos, I don't know if we could merge it how it looks now (at least on iOS 12.4). We should discuss that if it is impossible to resolve them in `UICollectionView` (is it?) we should move to `UIStackView` before merging that to develop branch.

    https://user-images.githubusercontent.com/5610904/142144088-aec9fa06-3b48-4aa3-af3d-13339f220689.mov


1. Hint button doesn’t match the design’s color (I think something wrong with the alpha component)
1. Clear button color doesn’t match hint button’s color.
1. Margins or paddings for the clear and the hint buttons are not the same.

2021-11-17 06:07 UTC, Sorix commented on Sources/UI/Scenes/Input/Table/Cell/Input.Table.TextFieldViewCell.swift
> +            let textFieldBottomAnchor = textInputView.bottomAnchor.constraint(lessThanOrEqualTo: contentView.bottomAnchor, constant: -10)
Could you name `-10`?

2021-11-18 19:54 UTC, Sorix approved these changes

2021-11-19 11:42 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +//        }
Last time @siebeprojects reviewed my code, he asked not to commit commented code blocks. If you want still to commit with comments, there is no need in constant `animated` above https://github.com/optile/checkout-ios/blob/e29e328c99c54fa0c3839a0ec7882d857a39f6ef/Sources/UI/Components/TextInputView/TextInputView.swift#L105

2021-11-19 11:42 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +//        }
Isn't it better to remove `animated` argument from `setStatus` method. And add `- TODO: ` note to set it later when we migrate to `UIStackView`?
https://github.com/optile/checkout-ios/blob/e29e328c99c54fa0c3839a0ec7882d857a39f6ef/Sources/UI/Components/TextInputView/TextInputView.swift#L97-L101

2021-11-19 11:42 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +//        }
By the way, when I checked that change on a simulator I didn't notice any visual changes.

2021-11-19 11:50 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
>      private func updateAppearance(animated: Bool) {
Isn't it better to remove `animated` argument. And add `- TODO: ` note to set it later when we migrate to `UIStackView`? If I correctly understand the change.

```suggestion
    // - TODO: return `animated` argument when we resolve issues with UICollectionView animation (see: https://github.com/optile/checkout-ios/pull/154#pullrequestreview-807716808)
    private func updateAppearance() {
```

2021-11-19 14:42 UTC, caiomello commented on Sources/UI/Components/TextInputView/TextInputView.swift
>      private func updateAppearance(animated: Bool) {
I see two options here:

1. We keep the current code as intact as possible while disabling animations (the way it is now)
2. We remove all animation code as if it never existed in the first place

I chose 1 because I think this code is really valuable, I really want to have this enabled again and the UI working really well as it should, and also I don't know when we'll be able to get it done and it'd be great if when the time comes we can just change these 2 small things and get the original functionality back.

@siebeprojects @Sorix I'm looking forward to hearing your opinions on this.

2021-11-19 15:11 UTC, siebeprojects commented on Sources/UI/Components/TextInputView/TextInputView.swift
>      private func updateAppearance(animated: Bool) {
@caiomello when the TextInputView has the option to either enable/disable animations then we should use that functionality ourselves to disable animations if we do not want it at the moment.
Either we set the Default value to "false", or we initialise all TextInputViews with the animation flag to false.

2021-11-19 15:11 UTC, siebeprojects commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +        // Animations are turned off for now so they don't conflict with UICollectionView reload animations.
There is no need to disable / comment this code because we could just initialise every TextInputView with the animation flag set to false.

2021-11-19 15:16 UTC, caiomello commented on Sources/UI/Components/TextInputView/TextInputView.swift
>      private func updateAppearance(animated: Bool) {
You are absolutely correct @siebeprojects! That's definitely the way to go. The component provides the functionality, it's up to the example app to decide if it animates or not of course. I don't know how that didn't occur to me 🤦🏻‍♂️

2021-11-22 10:35 UTC, Sorix reviewed
#### QA
- [ ] Return keys on a keyboard (_Next_, _Return_) seems don't work

2021-11-22 10:35 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +        setStatus(.normal)
What's the purpose of that call?

2021-11-22 10:46 UTC, caiomello commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +        setStatus(.normal)
Removing the error state when text changes. We might not need it though because state is being set by the delegate when focus changes instead... I'll double check.

2021-11-22 10:49 UTC, Sorix commented on Sources/UI/Components/TextInputView/TextInputView.swift
> +        setStatus(.normal)
Yes, we remove that status when text field receives focus outside of the component, so there is no need to reset an error state because in that case we have duplication.

2021-11-22 11:48 UTC, Sorix approved these changes

2021-11-22 12:51 UTC, siebeprojects approved these changes

2021-11-22 12:53 UTC, merged