[PCX-2363] Add support for Swift Package Manager
optile/checkout-ios pull request #158
Opened 2021-11-25 15:50 UTC by caiomello

2021-11-30 09:40 UTC, Fbada006 commented on .github/workflows/pullrequest.yml
> +      - feature/PCX-2363-spm
Why are you adding this here? I do not see why a feature branch needs to be added to the yml file. This means you will have to add something similar every time you have a new branch? You only need to do this for `develop` and/or `main` branches only unless I am missing something

2021-11-30 09:43 UTC, caiomello commented on .github/workflows/pullrequest.yml
> +      - feature/PCX-2363-spm
This was for testing. I just removed it, good catch!

2021-12-06 22:54 UTC, Sorix commented on Sources/Core/Bundle+Extensions.swift
> +#endif
Is it possible to indent `#if` statement, will it work?

2021-12-06 22:54 UTC, Sorix commented on Sources/UI/Model/Loadable.swift
> +        if let image = UIImage(named: identifier, in: Bundle.current, compatibleWith: nil) {
```suggestion
        if let image = UIImage(named: identifier, in: .current, compatibleWith: nil) {
```

2021-12-06 22:54 UTC, Sorix commented on Gemfile.lock
> +   2.2.22
Seems like you're using lower Bundler version, could you update it to the latest one?

2021-12-06 22:54 UTC, Sorix commented on Package.swift
> +    ],
Is it needed?

2021-12-06 22:54 UTC, Sorix commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
I think we need to specify the new path to resources here, why did you delete it?

```suggestion
  s.resources = ['Sources/Resources/*']
```

2021-12-06 22:54 UTC, Sorix commented on PayoneerCheckout.podspec
> -  s.frameworks = 'UIKit'
Why did you delete this line?

```suggestion
  s.frameworks = 'UIKit'
```

2021-12-07 09:32 UTC, caiomello commented on PayoneerCheckout.podspec
> -  s.frameworks = 'UIKit'
AFAIK this causes CocoaPods to include UIKit in the global header, meaning all files in the SDK implicitly import UIKit. Everything works fine after removing it, but there's very little documentation on this, so if you have more info let me know.

2021-12-07 09:47 UTC, caiomello commented on Package.swift
> +    ],
I usually like to leave it in because it's part of the generated syntax and we'll most likely use it soon, but I can remove it no problem.

2021-12-07 09:47 UTC, caiomello commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
Good catch!

2021-12-07 09:59 UTC, caiomello commented on Sources/Core/Bundle+Extensions.swift
> +#endif
Manually yes, but it's common practice to have pre-processor macros on column 0, and Xcode indents like this automatically.

2021-12-07 10:08 UTC, caiomello commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
I believe this is only needed if you want to expose resources to the host app. Everything works after removing it, but I'll  test some more.

2021-12-07 10:19 UTC, Sorix commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
The framework automatically downloads images when they're not found locally. Please check, if the framework is not downloading it from the internet after disabling this, it is okay.

2021-12-07 10:24 UTC, Sorix commented on PayoneerCheckout.podspec
> -  s.frameworks = 'UIKit'
At least here (https://guides.cocoapods.org/syntax/podspec.html#frameworks) I see that we should include all system framework we use. Despite the fact that I believe that everything can work without it I think it's safer to include it.

2021-12-07 10:26 UTC, Sorix commented on Package.swift
> +    ],
Just doesn't look nice :), but that is a matter of taste :). I will resolve that comment because it is more about decoration.

```suggestion
dependencies: [],
```

2021-12-07 10:40 UTC, Sorix commented on Gemfile.lock
> +   2.2.22
Resolved in f17003a

2021-12-07 10:41 UTC, caiomello commented on Package.swift
> +    ],
I removed it already, no worries.

2021-12-07 11:59 UTC, Sorix commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
You could add a breakpoint here to check this:
https://github.com/optile/checkout-ios/blob/4568c6205bea169959be3f59fbb4011e281db7fe/Sources/UI/Service/PaymentSessionService/DataDownloadProvider.swift#L30-L37

And check output as well it should be triggered as well: https://github.com/optile/checkout-ios/blob/4568c6205bea169959be3f59fbb4011e281db7fe/Sources/Network/Requests/DownloadData.swift#L31

2021-12-08 10:59 UTC, caiomello commented on PayoneerCheckout.podspec
> -  s.resources = ['Sources/Assets/*']
Updated in https://github.com/optile/checkout-ios/pull/158/commits/7e4d918829d1992e9b66075d4c4b2202e58e82a3. Thanks for pointing this out and for the thorough review!

2021-12-10 10:05 UTC, Sorix submitted a review, later dismissed

2021-12-10 10:21 UTC, siebeprojects commented on Example/Sources/Swift/Info.plist
> +	<string>Example</string>
Android has two example apps. 

1. Shop Example
2. Checkout Example

Both SDKs should have the same naming, so also iOS should name it “Checkout Example” and not “Example”.
Later, we may add also a “Shop Example” to iOS SDK, so then also in iOS we will have “Shop Example” and “Checkout Example”.

2021-12-10 12:52 UTC, Sorix requested changes

2021-12-10 12:52 UTC, Sorix commented on CheckoutExample/Sources/Swift/Info.plist
> +	<string>Checkout</string>
```suggestion
	<string>Checkout Example</string>
```

2021-12-10 14:58 UTC, Sorix approved these changes

2021-12-12 23:43 UTC, Sorix approved these changes

2021-12-13 12:49 UTC, siebeprojects approved these changes

2021-12-13 12:57 UTC, merged